config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
     get '/users/sign_in', :to => 'devise/sessions#new'
     get '/users/sign_out', :to => 'devise/sessions#destroy'
  end
  root 'diabetics#index'
  
  resources :diabetics do
    collection do 
      get 'monthly_report'
      get 'month_to_date'
    end
  end
    

   

end

app/models/diabetic.rb
class Diabetic < ActiveRecord::Base

  belongs_to :user
	validate :user_quota, :on => :create

  scope :filter_range,->(from, to) { where("created_at >= :from AND created_at <= :to", from: DateTime.parse(from).beginning_of_day, to: DateTime.parse(to).end_of_day) if from && to }
 #  scope :filter_range,->(from, to) { where("created_at >= :from AND created.at <= :to", from: Time.zone.parse(from).beginning_of_day, to: Time.zone.parse(to).end_of_day) if from && to }  

 # scope :filter_range,->(from, to) { where("orders.created >= :from AND orders.created <= :to", from: Time.zone.parse(from).beginning_of_day, to: Time.zone.parse(to).end_of_day) if from && to }
  
	private 
  def user_quota
    if user.diabetics.today.count >= 4
      errors.add(:base, "Exceeds daily limit. Daily limit is 4")
    end
  end

end

app/controllers/diabetics_controller.rb
class DiabeticsController < ApplicationController

	def index
		@diabetics = Diabetic.where("user_id = :user_id and Date(created_at) = :date", { user_id: current_user.id, date: Date.today })
		respond_to do |format|
			format.html { render "index" }
			format.xlsx { render xlsx: "diabetics", filename: "diabetics.xlsx" }
		end
		#@diabetics = Diabetic.where("created_at >= ?", Date.today)
	end

	def new
		@diabetic = Diabetic.new
	end

	def create
		#debugger
		@diabetic = Diabetic.new(user_params)
    	respond_to do |format|
      if @diabetic.save
        format.html { redirect_to diabetics_path, notice: 'successfully created.' }
      #  format.json { render :show, status: :created, location: @diabetic }
      else
        format.html { render :new }
        flash[:error] = "fsdgffdhg"
        format.json { render json: @diabetic.errors, status: :unprocessable_entity }
      end
    end
	end

	def month_to_date
		@month_to_date = Diabetic.filter_range(params[:from], params[:to])
		respond_to do |format|
			format.html { render "month_to_date" }
			format.xlsx { render xlsx: "month_to_date", filename: "month_to_date.xlsx" }
		end
	end
	
	 def monthly_report
	 	@diabetics = Diabetic.all
  	@monthly_report = @diabetics.group_by { |t| t.created_at.beginning_of_month }
  	respond_to do |format|
			format.html { render "monthly_report" }
			format.xlsx { render xlsx: "monthly_report", filename: "monthly_report.xlsx" }
		end
	 end

	private

	def user_params
    params.require(:diabetic).permit(:blood_level,:user_id)
  end

  # def month_report
  # 	params.require(:diabetic).permit(:from, :to)
  # end

end

app/views/diabetics/index.html.erb
<img src="../../assets/blood_glucose.jpg" class="img-responsive" alt="Responsive image"/>
<div class="caption-full">
  <%= link_to 'Report', diabetics_path(params.merge(format: "xlsx")), :class =>"btn btn-info btn-sm buton-right" %>
  <h4><a href="#">Blood Glucose Chart</a></h4>
  <table class="table">
    <thead>
      <tr>
        <th>Sugar Level</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @diabetics.each do |diabetic| %>
        <tr>
          <td><%= diabetic.blood_level %> mg/dl</td>
          <td>Today at <%= diabetic.created_at.strftime("%I:%M %P") %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
 

app/views/diabetics/month_to_date.html.erb
<div class="caption-full">
	<div class="test-sugar">
		<%= form_tag month_to_date_diabetics_path, :method => "get" do  %>
			<div class="form-group">
				<label> From</label>
					<%= text_field_tag :from, params[:from] %>
				<label> To</label>
					<%= text_field_tag :to, params[:to] %>
			</div>
			<div class="month-submit">
				<%= submit_tag "Search", :class => "btn btn-primary btn-sm" %>
				<%= link_to 'Report', month_to_date_diabetics_path(params.merge(format: "xlsx")), :class =>"btn btn-info btn-sm" %>
			</div>
		<% end %>
	</div>
	<% if params[:from] && params[:to]%>
		<table class="table">
		  <thead>
		    <tr>
		      <th>Sugar Level</th>
		      <th>Date</th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @month_to_date.each do |report| %>
		      <tr>
		        <td><%= report.blood_level %> mg/dl</td>
		        <td><%= report.created_at.strftime("%d %B %Y") %></td>
		      </tr>
		    <%end%>
		  </tbody>
		</table>
	<% end %>
</div>



<script type="text/javascript">
$(document).ready(function () {
	$("#from").datepicker({
                    changeMonth: true,
                    changeYear: true,
                    showButtonPanel: true,
                    dateFormat: 'yy-mm-dd'
                });
	$("#to").datepicker({
                    changeMonth: true,
                    changeYear: true,
                    showButtonPanel: true,
                    dateFormat: 'yy-mm-dd'
                });
});
</script>

app/views/diabetics/monthly_report.html.erb
<div class="caption-full">
	<%= link_to 'Report', monthly_report_diabetics_path(params.merge(format: "xlsx")), :class =>"btn btn-info btn-sm buton-right" %>
	<table class="table">
		<% @monthly_report.keys.sort.reverse.each do |month| %>
		  <thead>
		  <th><%= month.strftime("%B %Y") %></th><br/>
		    <tr>
		      <th>Sugar Level</th>
		      <th>Date</th>
		    </tr>
		  </thead>
		  <tbody>
		    <% for diabetic in @monthly_report[month] %>
		      <tr>
		        <td><%= diabetic.blood_level %> mg/dl</td>
		        <td><%= diabetic.created_at.strftime("%d %B %Y") %></td>
		      </tr>
		    <%end%>
		  </tbody>
	  <% end %>
	</table>
</div>

app/views/diabetics/new.html.erb
<div class="caption-full">
<div class="test-sugar">
	<p class="test-title">Test Your Blood Sugar With Diabetes</p>
	<%= form_for(@diabetic) do |f| %>
	  <div class="form-group">
	    <%= f.number_field :blood_level, :min => 1, :max => 9 %> mg/dl
	    <label class="error"></label>
	  </div>
	    <%= f.hidden_field  :user_id, :value => current_user.id %>
	  <% if @diabetic.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @diabetic.errors.full_messages.each do |message| %>
        <label class="error msg"><%= message %></label>
      <% end %>
      </ul>
    </div>
  <% end %>   
	  <div class="actions">
	    <%= f.submit "Test Diabetic", :class => "btn btn-primary btn-sm"%>
	  </div>
	<% end %>
</div>
</div>


<script type="text/javascript">
$(document).ready(function () {
  $("#new_diabetic").validate({
    rules:{
      "diabetic[blood_level]":
        {
        required: true
       }
    },
    messages: {
      "diabetic[blood_level]":
        {
        required:"Please Enter value"
        }
    }
  });
});
</script>