config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
     get '/users/sign_in', :to => 'devise/sessions#new'
     get '/users/sign_out', :to => 'devise/sessions#destroy'
  end
  root 'diabetics#index'
  
  resources :diabetics do
    collection do 
      get 'monthly_report'
      get 'month_to_date'
    end
  end
    

   

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<%= render "partials/google_analytics" %>
  	<title>Blood Glucose Level</title>
  	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

  	<%= stylesheet_link_tag    'application', 'thickbox', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application','jquery-1.3.2.min', 'jquery.validate.min', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
  	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	</head>
	<body>
	<%# if current_user %>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Glucose Level</a>
	    </div>
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <% if current_user %>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav top-menu">
	      	<li>
	      		<%= link_to 'Track Blood Glucose', new_diabetic_path %>
	      	</li>
	      	<li>
	      	<li>
	      		<a><%= current_user.email%></a>
	      	<li>
	      	<li>
	          <%= link_to "Log out", destroy_user_session_path%>
	      	</li>
	      </ul>
	    </div>
	    <% end %>
	    <!-- /.navbar-collapse -->
	  </div>
	    <!-- /.container -->
	</nav>

    <!-- Page Content -->
	<div class="container">
  	<div class="row">
    	<div class="col-md-3">
      	<p class="lead">Reports</p>
      	<div class="list-group">
          <a href="/diabetics" class="list-group-item active">Daily Report</a>
          <a href="/diabetics/month_to_date" class="list-group-item">Month to Date Report</a>
          <a href="/diabetics/monthly_report" class="list-group-item">Monthly Report</a>
      	</div>
    	</div>
    	<div class="col-md-9">
				<div class="thumbnail glucose-img">
    			<%= yield %>
    		</div>
    	</div>
		</div>
	</div>
    <!-- /.container -->
<%# end %>
<%= render "partials/google_analytics_pageview" %>
</body>
</html>